---
title: First Post 
author: "Jagger V"
date: '2018-11-16'
slug: hello-world-rmd
categories: ["R"]
tags: ["Test"]
---


**Does it work?** Seems like it does. This is my first blog post! I wanted to create my own blog using R programming, R Studio, Git, and Github where I would host my personal site and opinions. These opinions will not be fabricated and will be based off my personal own analysis. 

**Why start a blog?**
I have a huge passion for analyzing financial data, especially those 10-K's and 10-Q's!! I do not get excited from fleshing out models on excel all day, but I do get excited from the picture painted using all the tools these filings provide. To most, a 10-k just a 75+ page document full of financial jargon and data. To me, I see a bunch of puzzle pieces that each individual / analyst puts together in their own uique way. I find the difference in the outcomes extremely fascinaitng since each analyst is seeing and hearing the same information as the other (I know some analyst go a step further to getting a better edge in the available data, such as channel checks through other sources). Where they start to diverge from the other analyst is what they do next with that information. I've been running my own analysis on different public comapnies that interests me, and I would like to publish my opinions so I can receive feedback and meet others with similiar passions. There is so much information and data in the world of finance, so much that I know it is impossible to learn all of it. My goal is to find which of this information available today and in the future, is important and benefitial to my career and my personal life. 

